language:generic
#required super user access
sudo: required
#services that are required
services:
 - docker
#steps before the test
before_install:
 - docker build -t mariniija/docker-react -f Dockerfile.dev .
#triggering travis-ci to run this script to have the test
script:
 - docker run -e CI=true mariniija/docker-react npm run test -- --watchAll=false

